using SDG.Framework.Debug.Parsers;
using SDG.Unturned;
using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Diagnostics.SymbolStore;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace MetadataTesting.Variables
{
    public static class Unturned
    {
        public enum Rarity
        {
            Common,
            Uncommon,
            Rare,
            Epic,
            Legendary
        }
        public enum FireRate
        {
            Safety,
            Semi,
            Auto,
            Burst
        }
        public enum Water
        {
            Empty,
            Clean,
            Salty,
            Dirty,
            Toxic
        }
        public enum ItemType
        {
            Weapon,
            Water,
            Gas,
            Togglable,
            Other
        }
        public static string nameFromID(ushort itemID)
        {
            //Dictionary to convert item IDs to names.
            Dictionary<int, string> unturnedItems = new Dictionary<int, string>
            {
                { 2, "Work Jeans" },
                { 3, "Orange Hoodie" },
                { 4, "Eaglefire" },
                { 5, "Eaglefire Iron Sights" },
                { 6, "Military Magazine" },
                { 7, "Military Suppressor" },
                { 8, "Vertical Grip" },
                { 9, "Red Daypack" },
                { 10, "Police Vest" },
                { 11, "Red Bandana" },
                { 13, "Canned Beans" },
                { 14, "Bottled Water" },
                { 15, "Medkit" },
                { 16, "Camp Axe" },
                { 17, "Military Drum" },
                { 18, "Timberwolf" },
                { 19, "Timberwolf Iron Sights" },
                { 20, "Timberwolf Magazine" },
                { 21, "8x Scope" },
                { 22, "Red Cross Scope" },
                { 27, "Tophat" },
                { 28, "Gas Can (Portable)" },
                { 29, "Maple Fortification" },
                { 30, "Maple Barricade" },
                { 31, "Maple Floor" },
                { 32, "Maple Doorway" },
                { 33, "Maple Wall" },
                { 34, "Maple Window" },
                { 35, "Maple Roof" },
                { 36, "Maple Pillar" },
                { 37, "Birch Log" },
                { 38, "Birch Stick" },
                { 39, "Maple Log" },
                { 40, "Maple Stick" },
                { 41, "Pine Log" },
                { 42, "Pine Stick" },
                { 43, "Low Caliber Military Ammunition Crate" },
                { 44, "Low Caliber Civilian Ammunition Box" },
                { 45, "Birch Barricade" },
                { 46, "Pine Barricade" },
                { 47, "Birch Fortification" },
                { 48, "Pine Fortification" },
                { 49, "Birch Doorway" },
                { 50, "Pine Doorway" },
                { 51, "Birch Floor" },
                { 52, "Pine Floor" },
                { 53, "Birch Pillar" },
                { 54, "Pine Pillar" },
                { 55, "Birch Roof" },
                { 56, "Pine Roof" },
                { 57, "Birch Wall" },
                { 58, "Pine Wall" },
                { 59, "Birch Window" },
                { 60, "Pine Window" },
                { 61, "Maple Plank" },
                { 62, "Birch Plank" },
                { 63, "Pine Plank" },
                { 64, "Rope" },
                { 65, "Wire" },
                { 66, "Cloth" },
                { 67, "Metal Scrap" },
                { 68, "Metal Sheet" },
                { 69, "Tape" },
                { 70, "Glue" },
                { 71, "Nails" },
                { 72, "Can" },
                { 73, "Explosives (Raw)" },
                { 74, "Bricks" },
                { 75, "Chemicals" },
                { 76, "Blowtorch" },
                { 77, "Canned Tomato Soup" },
                { 78, "Canned Chicken Soup" },
                { 79, "Canned Tuna" },
                { 80, "Canned Cola" },
                { 81, "MRE" },
                { 82, "Chips" },
                { 83, "Chocolate Bar" },
                { 84, "Candy Bar" },
                { 85, "Granola Bar" },
                { 86, "Energy Bar" },
                { 87, "Canned Pasta" },
                { 88, "Canned Bacon" },
                { 89, "Canned Beef" },
                { 90, "Canned Sardines" },
                { 91, "Apple Juice" },
                { 92, "Grape Juice" },
                { 93, "Bottled Energy" },
                { 94, "Bottled Coconut" },
                { 95, "Bandage" },
                { 96, "Splint" },
                { 97, "Colt" },
                { 98, "Colt Magazine" },
                { 99, "Cobra" },
                { 100, "Cobra Magazine" },
                { 101, "Schofield" },
                { 102, "Schofield Iron Sights" },
                { 103, "Schofield Clip" },
                { 104, "Fire Axe" },
                { 105, "Baseball Bat" },
                { 106, "Hockey Stick" },
                { 107, "Ace" },
                { 108, "Ace Clip" },
                { 109, "Hawkhound" },
                { 110, "Hawkhound Iron Sights" },
                { 111, "Hawkhound Magazine" },
                { 112, "Bluntforce" },
                { 113, "12 Gauge Shells" },
                { 114, "Bluntforce Iron Sights" },
                { 115, "Pink Berry (Raw Mauve Berries)" },
                { 116, "Honeybadger" },
                { 118, "Honeybadger Iron Sights" },
                { 119, "Low Caliber Ranger Ammunition Box" },
                { 120, "Kitchen Knife" },
                { 121, "Military Knife" },
                { 122, "Zubeknakov" },
                { 123, "Ranger Magazine" },
                { 124, "Zubeknakov Iron Sights" },
                { 125, "Ranger Drum" },
                { 126, "Nykorev" },
                { 127, "Nykorev Box" },
                { 128, "Nykorev Iron Sights" },
                { 129, "Snayperskya" },
                { 130, "Snayperskya Magazine" },
                { 131, "Snayperskya Iron Sights" },
                { 132, "Dragonfang" },
                { 133, "Dragonfang Box" },
                { 134, "Dragonfang Iron Sights" },
                { 135, "Golf Club" },
                { 136, "Sledgehammer" },
                { 137, "Butcher Knife" },
                { 138, "Hammer" },
                { 139, "Swiss Knife" },
                { 140, "Butterfly Knife" },
                { 141, "Saw" },
                { 142, "Rake" },
                { 143, "Bipod" },
                { 144, "Ranger Suppressor" },
                { 145, "Horizontal Grip" },
                { 146, "Red Dot Sight" },
                { 147, "Red Halo Sight" },
                { 148, "Red Chevron Scope" },
                { 149, "Military Barrel" },
                { 150, "Military Muzzle" },
                { 151, "Tactical Laser" },
                { 152, "Tactical Light" },
                { 153, "7x Scope" },
                { 154, "Orange Shirt" },
                { 155, "Orange Tee" },
                { 156, "Orange Parka" },
                { 157, "Purple Hoodie" },
                { 158, "Purple Shirt" },
                { 159, "Purple Tee" },
                { 160, "Purple Parka" },
                { 161, "Green Hoodie" },
                { 162, "Green Parka" },
                { 163, "Green Shirt" },
                { 164, "Green Tee" },
                { 165, "Red Hoodie" },
                { 166, "Red Parka" },
                { 167, "Red Shirt" },
                { 168, "Red Tee" },
                { 169, "Yellow Hoodie" },
                { 170, "Yellow Parka" },
                { 171, "Yellow Shirt" },
                { 172, "Yellow Tee" },
                { 173, "Blue Hoodie" },
                { 174, "Blue Parka" },
                { 175, "Blue Shirt" },
                { 176, "Blue Tee" },
                { 177, "White Hoodie" },
                { 178, "White Parka" },
                { 179, "White Shirt" },
                { 180, "White Tee" },
                { 181, "Black Hoodie" },
                { 182, "Black Parka" },
                { 183, "Black Shirt" },
                { 184, "Black T-Shirt" },
                { 185, "Black Bandana" },
                { 186, "Blue Bandana" },
                { 187, "Green Bandana" },
                { 188, "Orange Bandana" },
                { 189, "Purple Bandana" },
                { 190, "White Bandana" },
                { 191, "Yellow Bandana" },
                { 192, "Black Toque" },
                { 193, "Blue Toque" },
                { 194, "Green Toque" },
                { 195, "Orange Toque" },
                { 196, "Purple Toque" },
                { 197, "Red Toque" },
                { 198, "White Toque" },
                { 199, "Yellow Toque" },
                { 200, "Black Daypack" },
                { 201, "Blue Daypack" },
                { 202, "Green Daypack" },
                { 203, "Orange Daypack" },
                { 204, "Purple Daypack" },
                { 205, "White Daypack" },
                { 206, "Yellow Daypack" },
                { 207, "Outfit Jeans" },
                { 208, "Cowboy Jeans" },
                { 209, "Cargo Pants" },
                { 210, "Buds" },
                { 211, "Plaid Shirt" },
                { 212, "Khaki Pants" },
                { 213, "Corduroy Pants" },
                { 214, "Trouser Pants" },
                { 215, "Black Sweatervest" },
                { 216, "Blue Sweatervest" },
                { 217, "Green Sweatervest" },
                { 218, "Orange Sweatervest" },
                { 219, "Purple Sweatervest" },
                { 220, "Red Sweatervest" },
                { 221, "White Sweatervest" },
                { 222, "Yellow Sweatervest" },
                { 223, "Police Top" },
                { 224, "Police Bottom" },
                { 225, "Police Cap" },
                { 226, "Khaki Shorts" },
                { 227, "Cargo Shorts" },
                { 228, "Corduroy Shorts" },
                { 229, "Trouser Shorts" },
                { 230, "Chef Top" },
                { 231, "Chef Bottom" },
                { 232, "Construction Top" },
                { 233, "Firefighter Top" },
                { 234, "Firefighter Bottom" },
                { 235, "Ghillie Top" },
                { 236, "Ghillie Bottom" },
                { 237, "Ghillie Hood" },
                { 238, "Ghillie Vest" },
                { 239, "Chef Hat" },
                { 240, "Construction Helmet" },
                { 241, "Firefighter Helmet" },
                { 242, "Farmer Top" },
                { 243, "Farmer Bottom" },
                { 244, "Farmer Hat" },
                { 245, "Black Travelpack" },
                { 246, "Blue Travelpack" },
                { 247, "Green Travelpack" },
                { 248, "Orange Travelpack" },
                { 249, "Purple Travelpack" },
                { 250, "Red Travelpack" },
                { 251, "White Travelpack" },
                { 252, "Yellow Travelpack" },
                { 253, "Alicepack" },
                { 254, "Fragmentation Grenade" },
                { 255, "Blue Flare" },
                { 256, "Green Flare" },
                { 257, "Orange Flare" },
                { 258, "Purple Flare" },
                { 259, "Red Flare" },
                { 260, "Yellow Flare" },
                { 261, "Black Smoke" },
                { 262, "Blue Smoke" },
                { 263, "Green Smoke" },
                { 264, "Orange Smoke" },
                { 265, "Purple Smoke" },
                { 266, "Red Smoke" },
                { 267, "White Smoke" },
                { 268, "Yellow Smoke" },
                { 269, "Vaccine" },
                { 270, "Raw Amber Berry" },
                { 271, "Raw Indigo Berry" },
                { 272, "Raw Jade Berry" },
                { 273, "Raw Russet Berry" },
                { 274, "Raw Teal Berry" },
                { 275, "Raw Vermillion Berry" },
                { 276, "Flashlight" },
                { 277, "Carjack (Car Lift)" },
                { 278, "Santa Hat" },
                { 279, "Santa Top" },
                { 280, "Santa Bottom" },
                { 281, "Maple Door" },
                { 282, "Birch Door" },
                { 283, "Pine Door" },
                { 284, "Jail Door" },
                { 285, "Metal Bar" },
                { 286, "Vault Door" },
                { 287, "Bar Fortification" },
                { 288, "Black Bedroll" },
                { 289, "Blue Bedroll" },
                { 290, "Green Bedroll" },
                { 291, "Orange Bedroll" },
                { 292, "Purple bedroll" },
                { 293, "Red Bedroll" },
                { 294, "White Bedroll" },
                { 295, "Yellow Bedroll" },
                { 296, "16x Scope" },
                { 297, "Grizzly" },
                { 298, "Grizzly Magazine" },
                { 299, "Grizzly Iron Sights" },
                { 300, "Shadowstalker" },
                { 301, "Rail" },
                { 302, "Shadowstalker Scope" },
                { 303, "Prisoner Top" },
                { 304, "Prisoner Bottom" },
                { 305, "RCMP Bottom" },
                { 306, "RCMP Top" },
                { 307, "Forest Military Top" },
                { 308, "Forest Military Bottom" },
                { 309, "Forest Military Helmet" },
                { 310, "Forest Military Vest" },
                { 311, "Medic Top" },
                { 312, "Medic Bottom" },
                { 313, "RCMP Hat" },
                { 314, "Grocer Top" },
                { 315, "Grocer Bottom" },
                { 316, "Maple Stairs" },
                { 317, "Pine Stairs" },
                { 318, "Birch Stairs" },
                { 319, "Maple Hole" },
                { 320, "Pine Hole" },
                { 321, "Birch Hole" },
                { 322, "Maple Ramp" },
                { 323, "Birch Ramp" },
                { 324, "Pine Ramp" },
                { 325, "Maple Ladder" },
                { 326, "Birch Ladder" },
                { 327, "Pine Ladder" },
                { 328, "Metal Locker" },
                { 329, "Carrot" },
                { 330, "Carrot Seed" },
                { 331, "Planter" },
                { 332, "Fertilizer" },
                { 333, "Binoculars" },
                { 334, "Military Nightvision" },
                { 335, "Corn" },
                { 336, "Corn Seed" },
                { 337, "Canteen" },
                { 338, "Lettuce" },
                { 339, "Lettuce Seed" },
                { 340, "Tomato" },
                { 341, "tomato Seed" },
                { 342, "Potato" },
                { 343, "Potato Seed" },
                { 344, "Wheat" },
                { 345, "Wheat Seed" },
                { 346, "Crossbow" },
                { 347, "Arrow" },
                { 348, "Maple Arrow" },
                { 349, "Crossbow Iron Sights" },
                { 351, "Birch Arrow" },
                { 352, "Pine Arrow" },
                { 353, "Maple Bow" },
                { 355, "Birch Bow" },
                { 356, "Pine Bow" },
                { 357, "Compound Bow" },
                { 358, "Compound Iron Sights" },
                { 359, "Maple Torch" },
                { 360, "Birch Torch" },
                { 361, "Pine Torch" },
                { 362, "Campfire" },
                { 363, "Maplestrike" },
                { 364, "Maplestrike Iron Sights" },
                { 365, "Sandbag" },
                { 366, "Maple Crate" },
                { 367, "Birch Crate" },
                { 368, "Pine Crate" },
                { 369, "Metal Floor" },
                { 370, "Metal Doorway" },
                { 371, "Metal Wall" },
                { 372, "Metal Window" },
                { 373, "Metal Roof" },
                { 374, "Metal Pillar" },
                { 375, "Metal Stairs" },
                { 376, "Metal Hole" },
                { 377, "Metal Ramp" },
                { 378, "Metal Door" },
                { 379, "Metal Ladder" },
                { 380, "Masterkey" },
                { 381, "20 Gauge Shells" },
                { 382, "Caltrop" },
                { 383, "Maple Spikes" },
                { 384, "Birch Spikes" },
                { 385, "Pine Spikes" },
                { 386, "Barbed Wire" },
                { 387, "Adrenaline" },
                { 388, "Morphine" },
                { 389, "Antibiotics" },
                { 390, "Painkillers" },
                { 391, "Vitamins" },
                { 392, "Purification Tablets" },
                { 393, "Rag" },
                { 394, "Dressing" },
                { 395, "Blood Bag" },
                { 396, "Crushed Mauve Berries (Refined)" },
                { 397, "Crushed Amber Berries (Refined)" },
                { 398, "Crushed Indigo Berries (Refined)" },
                { 399, "Crushed Jade Berries (Refined)" },
                { 400, "Crushed Russet Berries (Refined)" },
                { 401, "Crushed Teal Berries (Refined)" },
                { 402, "Crushed Vermillion Berries (Refined)" },
                { 403, "Suturekit" },
                { 404, "Cough Syrup" },
                { 405, "Mechanic Top" },
                { 406, "Mechanic Bottom" },
                { 407, "Engineer Top" },
                { 408, "Engineer Bottom" },
                { 410, "Black Poncho" },
                { 411, "Blue Poncho" },
                { 412, "Green Poncho" },
                { 413, "Orange Poncho" },
                { 414, "Purple Poncho" },
                { 415, "Red Poncho" },
                { 416, "White Poncho" },
                { 417, "Yellow Poncho" },
                { 420, "Biker Jacket" },
                { 421, "Suit Top" },
                { 422, "Suit Bottom" },
                { 423, "Engineer Hat" },
                { 424, "Fedora" },
                { 425, "Black Cap" },
                { 426, "Blue Cap" },
                { 427, "Green Cap" },
                { 428, "Orange Cap" },
                { 429, "Purple Cap" },
                { 430, "Red Cap" },
                { 431, "White Cap" },
                { 432, "Yellow Cap" },
                { 433, "Desert Beret" },
                { 434, "Black Balaclava" },
                { 435, "Blue Balaclava" },
                { 436, "Green Balaclava" },
                { 437, "Orange Balaclava" },
                { 438, "Purple Balaclava" },
                { 439, "Red Balaclava" },
                { 440, "White Balaclava" },
                { 441, "Yellow Balaclava" },
                { 442, "Maple Rampart" },
                { 443, "Maple Post" },
                { 444, "Birch Rampart" },
                { 445, "Pine Rampart" },
                { 446, "Metal Rampart" },
                { 447, "Birch Post" },
                { 448, "Pine Post" },
                { 449, "Metal Post" },
                { 450, "Maple Garage" },
                { 451, "Maple Gate" },
                { 452, "Birch Garage" },
                { 453, "Pine Garage" },
                { 454, "Metal Garage" },
                { 455, "Birch Gate" },
                { 456, "Pine Gate" },
                { 457, "Metal Gate" },
                { 458, "Generator" },
                { 459, "Spotlight" },
                { 460, "Bread" },
                { 461, "Tuna Sandwich" },
                { 462, "Milk Box" },
                { 463, "Orange Juice" },
                { 464, "Cheese" },
                { 465, "Soda" },
                { 466, "Grilled Cheese Sandwich" },
                { 467, "BLT Sandwich" },
                { 468, "Ham Sandwich" },
                { 469, "Canned Ham" },
                { 470, "Eggs" },
                { 471, "Cake" },
                { 472, "Bottled Cola" },
                { 473, "Bottled Soda" },
                { 474, "Maple Rifle" },
                { 475, "Rifle Iron Sights" },
                { 476, "Makeshift Scope" },
                { 477, "Makeshift Muffler" },
                { 478, "Rifle Clip" },
                { 479, "Birch Rifle" },
                { 480, "Pine Rifle" },
                { 481, "Maple Bottle" },
                { 482, "Birch Bottle" },
                { 483, "Pine Bottle" },
                { 484, "Sportshot" },
                { 485, "Sportshot Magazine" },
                { 486, "Sportshot Iron Sights" },
                { 487, "Makeshift Bat" },
                { 488, "Desert Eagle (Desert Falcon)" },
                { 489, "Desert Eagle Magazine (Desert Falcon Magazine)" },
                { 490, "Chainsaw" },
                { 491, "Gold Aviators" },
                { 503, "Fishing Rod" },
                { 504, "Raw Trout" },
                { 505, "Raw Salmon" },
                { 506, "Birch Rod" },
                { 507, "Maple Rod" },
                { 508, "Pine Rod" },
                { 509, "Fishing Hat" },
                { 510, "Fishing Top" },
                { 511, "Fishing Bottom" },
                { 512, "Cooked Trout" },
                { 513, "Cooked Salmon" },
                { 514, "Raw Venison" },
                { 515, "Cooked Venison" },
                { 516, "Leather" },
                { 517, "Leather Top" },
                { 518, "Leather Bottom" },
                { 519, "Rocket Launcher" },
                { 520, "Rocket" },
                { 521, "Rocket Iron Sights" },
                { 548, "Designer Jeans" },
                { 727, "Medic Glasses" },
                { 892, "Small One Way Plate" },
                { 893, "Small Bulletproof Plate" },
                { 894, "Small Weak Plate" },
                { 1000, "Matamorez" },
                { 1001, "Matamorez Iron Sights" },
                { 1002, "Matamorez Barrel (Unobtainable)" },
                { 1003, "Matamorez Magazine" },
                { 1004, "Red Kobra Sight" },
                { 1005, "Matamorez Box" },
                { 1006, "Cobra Box" },
                { 1007, "Adaptive Chambering Attachment" },
                { 1008, "Rangefinder" },
                { 1009, "Desert Beret" },
                { 1010, "Desert Military Helmet" },
                { 1011, "Desert Military Top" },
                { 1012, "Desert Military Bottom" },
                { 1013, "Desert Military Vest" },
                { 1014, "Leather Pack" },
                { 1015, "Biohazard Top" },
                { 1016, "Biohazard Bottom" },
                { 1017, "Biohazard Hood" },
                { 1018, "Sabertooth" },
                { 1019, "Sabertooth Iron Sights" },
                { 1020, "Sabertooth Magazine" },
                { 1021, "Avenger" },
                { 1022, "Avenger Magazine" },
                { 1023, "Police Baton" },
                { 1024, "Peacemaker" },
                { 1025, "Peacemaker Iron Sights" },
                { 1026, "Peacemaker Magazine" },
                { 1027, "Viper" },
                { 1028, "Viper Iron Sights" },
                { 1029, "Viper Magazine" },
                { 1030, "Frying Pan" },
                { 1031, "Shovel" },
                { 1032, "Crowbar" },
                { 1033, "Paddle" },
                { 1034, "Pitchfork" },
                { 1035, "Machete" },
                { 1036, "Katana" },
                { 1037, "Heartbreaker" },
                { 1038, "Heartbreaker Iron Sights" },
                { 1039, "Kryzkarek" },
                { 1040, "Kryzkarek Magazine" },
                { 1041, "Yuri" },
                { 1042, "Yuri Magazine" },
                { 1043, "Yuri Iron Sights" },
                { 1044, "Civilian Nightvision" },
                { 1045, "Pumpkin Seed" },
                { 1046, "Pumpkin" },
                { 1047, "Pumpkin Pie" },
                { 1048, "Hockey Mask" },
                { 1049, "Jack-o-Lantern Torch" },
                { 1050, "Safezone Radiator" },
                { 1051, "$5 Note" },
                { 1052, "$10 Note" },
                { 1053, "$20 Note" },
                { 1054, "$50 Note" },
                { 1055, "$100 Note" },
                { 1056, "Loonie" },
                { 1057, "Toonie" },
                { 1058, "Large Maple Plate" },
                { 1059, "Small Maple Plate" },
                { 1060, "Large Maple Frame" },
                { 1061, "Small Maple Frame" },
                { 1062, "Maple Siding" },
                { 1063, "Maple Pipe" },
                { 1064, "Large Birch Plate" },
                { 1065, "Small Birch Plate" },
                { 1066, "Large Birch Frame" },
                { 1067, "Small Birch Frame" },
                { 1068, "Birch Siding" },
                { 1069, "Birch Pipe" },
                { 1070, "Large Pine Plate" },
                { 1071, "Small Pine Plate" },
                { 1072, "Large Pine Frame" },
                { 1073, "Small Pine Frame" },
                { 1074, "Pine Siding" },
                { 1075, "Pine Pipe" },
                { 1076, "Amber Pie" },
                { 1077, "Indigo Pie" },
                { 1078, "Jade Pie" },
                { 1079, "Mauve Pie" },
                { 1080, "Russet Pie" },
                { 1081, "Teal Pie" },
                { 1082, "Vermillion Pie" },
                { 1083, "Maple Doorframe" },
                { 1084, "Maple Garageframe" },
                { 1085, "Birch Doorframe" },
                { 1086, "Birch Garageframe" },
                { 1087, "Pine Doorframe" },
                { 1088, "Pine Garageframe" },
                { 1089, "Metal Doorframe" },
                { 1090, "Metal Garageframe" },
                { 1091, "Large Metal Plate" },
                { 1092, "Small Metal Plate" },
                { 1093, "Metal Siding" },
                { 1094, "Metal Pipe" },
                { 1095, "Maple Sign" },
                { 1096, "Birch Sign" },
                { 1097, "Pine Sign" },
                { 1098, "Locked Metal Sign" },
                { 1099, "Makeshift Vehicle" },
                { 1100, "C4 Sticky Grenade" },
                { 1101, "Landmine" },
                { 1102, "Claymore" },
                { 1103, "Umbrella" },
                { 1104, "Amber Berry Seed" },
                { 1105, "Indigo Berry Seed" },
                { 1106, "Jade Berry Seed" },
                { 1107, "Mauve Berry Seed" },
                { 1108, "Russet Berry Seed" },
                { 1109, "Teal Berry Seed" },
                { 1110, "Vermillion Berry Seed" },
                { 1111, "6 Seater Makeshift Vehicle" },
                { 1112, "1 Seater Makeshift Vehicle" },
                { 1113, "Snare" },
                { 1114, "Maple Jerrycan" },
                { 1115, "Birch Jerrycan" },
                { 1116, "Pine Jerrycan" },
                { 1117, "Pork" },
                { 1118, "Bacon" },
                { 1119, "Barbwire Fence" },
                { 1120, "Raw Beef" },
                { 1121, "Cooked Beef" },
                { 1122, "Blue umbrella" },
                { 1123, "Green Umbrella" },
                { 1124, "Orange Umbrella" },
                { 1125, "Purple Umbrella" },
                { 1126, "Red Umbrella" },
                { 1127, "White umbrella" },
                { 1128, "Yellow Umbrella" },
                { 1129, "Heatstim" },
                { 1130, "Ornamental Barbed Wire" },
                { 1131, "Ornamental Barbed Wire Fence" },
                { 1132, "Snowball" },
                { 1133, "Black Scarf" },
                { 1134, "Blue Scarf" },
                { 1135, "Green Scarf" },
                { 1136, "Orange Scarf" },
                { 1137, "Purple Scarf" },
                { 1138, "Red Scarf" },
                { 1139, "White Scarf" },
                { 1140, "Yellow Scarf" },
                { 1143, "Sawed-off shotgun" },
                { 1144, "Large Birch Plate (Equilateral)" },
                { 1145, "Large Birch Plate (Right)" },
                { 1146, "Large Maple Plate (Equilateral)" },
                { 1147, "Large Maple Plate (Right)" },
                { 1148, "Large Pine Plate (Equilateral)" },
                { 1149, "Large Pine Plate Right" },
                { 1150, "Small Birch Plate (Equilateral)" },
                { 1151, "Small Birch Plate (Right)" },
                { 1152, "Small Maple Plate (Equilateral)" },
                { 1153, "Small Maple Plate (Right)" },
                { 1154, "Small Pine Plate (Equilateral)" },
                { 1155, "Small Pine Plate (Right)" },
                { 1156, "Thief Top" },
                { 1157, "Thief Bottom" },
                { 1158, "Claim Flag" },
                { 1159, "Maple Syrup" },
                { 1160, "Pancake" },
                { 1161, "Waffle" },
                { 1162, "Dough" },
                { 1163, "Doughnut" },
                { 1164, "Pizza" },
                { 1165, "Nailgun" },
                { 1166, "Nailgun magazine" },
                { 1168, "Civilian Armor Vest" },
                { 1169, "Spec Ops Vest" },
                { 1170, "Spec Ops Rucksack" },
                { 1171, "Spec Ops Top" },
                { 1172, "Spec Ops Bottom" },
                { 1173, "Makeshift Armor" },
                { 1174, "Scythe" },
                { 1175, "Chart" },
                { 1176, "GPS" },
                { 1177, "Military Tracer Magazine" },
                { 1178, "Diving Tank" },
                { 1179, "Wetsuit Top" },
                { 1180, "Wetsuit Bottom" },
                { 1181, "Snorkel" },
                { 1182, "Black Duffelbag" },
                { 1183, "Blue Duffelbag" },
                { 1184, "Green Duffelbag" },
                { 1185, "Orange Duffelbag" },
                { 1186, "Purple Duffelbag" },
                { 1187, "Red Duffelbag" },
                { 1188, "White Duffelbag" },
                { 1189, "Yellow Duffelbag" },
                { 1190, "Ranger Muzzle" },
                { 1191, "Ranger Barrell" },
                { 1192, "High Calibur Military Ammo" },
                { 1193, "High Calibur Ranger Ammo" },
                { 1194, "Horde Beacon" },
                { 1195, "Handcuffs" },
                { 1196, "Handcuffs Key" },
                { 1197, "Cable Tie" },
                { 1198, "Pickaxe" },
                { 1199, "Miner Lamp / Headlamp" },
                { 1200, "Military Fragmentation Magazine" },
                { 1201, "Military Nightvision Scope" },
                { 1202, "Maple Rifle Rack" },
                { 1203, "Birch Rifle Rack" },
                { 1204, "Pine Rifle Rack" },
                { 1205, "Maple Trophy Case" },
                { 1206, "Birch Trophy Case" },
                { 1207, "Pine Trophy Case" },
                { 1208, "Rain Barrel" },
                { 1209, "Explosive Arrow" },
                { 1210, "Brick Doorway" },
                { 1211, "Brick Garage" },
                { 1212, "Brick Pillar" },
                { 1213, "Brick Post" },
                { 1214, "Brick Rampart" },
                { 1215, "Brick Wall" },
                { 1216, "Brick Window" },
                { 1217, "Brick Doorframe" },
                { 1218, "Brick Garageframe" },
                { 1219, "Oil Derrick (Pump Jack)" },
                { 1220, "Metal Rifle Rack" },
                { 1221, "Metal Trophy Case" },
                { 1222, "Cagelight" },
                { 1223, "Maple Shutter" },
                { 1224, "Birch Shutter" },
                { 1225, "Pine Shutter" },
                { 1226, "Metal Shutter" },
                { 1227, "Tanktrap" },
                { 1228, "Water Tank" },
                { 1229, "Fuel Tank" },
                { 1230, "Industrial Generator" },
                { 1231, "Maple Flag" },
                { 1232, "Birch Flag" },
                { 1233, "Pine Flag" },
                { 1234, "Metal Flag" },
                { 1235, "Maple Doubledoor" },
                { 1236, "Birch Doubledoor" },
                { 1237, "Pine Doubledoor" },
                { 1238, "Metal Doubledoor" },
                { 1239, "Slippery Metal Plate" },
                { 1240, "Remote Detonator" },
                { 1241, "Breaching Charge (Demolition Charge)" },
                { 1242, "Makeshift Grenade" },
                { 1243, "Cot / Bedframe" },
                { 1244, "Sentry Gun / Auto Turret" },
                { 1245, "Maple Counter" },
                { 1246, "Birch Counter" },
                { 1247, "Pine Counter" },
                { 1248, "Metal Counter" },
                { 1249, "Fridge" },
                { 1250, "Oven" },
                { 1251, "Maple Counter Sink" },
                { 1252, "Birch Counter Sink" },
                { 1253, "Pine Counter Sink" },
                { 1254, "Metal Counter Sink" },
                { 1255, "Lamp" },
                { 1256, "Couch" },
                { 1257, "Maple Library" },
                { 1258, "Birch Library" },
                { 1259, "Pine Library" },
                { 1260, "Metal Library" },
                { 1261, "Oxygenator" },
                { 1262, "Triangular Maple Floor" },
                { 1263, "Triangular Birch Floor" },
                { 1264, "Triangular Pine Floor" },
                { 1265, "Triangular Metal Floor" },
                { 1266, "Triangular Maple Roof" },
                { 1267, "Triangular Birch Roof" },
                { 1268, "Triangular Pine Roof" },
                { 1269, "Triangular Metal Roof" },
                { 1270, "Gasmask" },
                { 1271, "Radiation Filter" },
                { 1272, "Wall mounted blue flare" },
                { 1273, "Wall mounted green flare" },
                { 1274, "Wall mounted orange flare" },
                { 1275, "Wall mounted purple flare" },
                { 1276, "Wall mounted red flare" },
                { 1277, "Wall mounted yellow flare" },
                { 1278, "Maple Wardrobe" },
                { 1279, "Birch Wardrobe" },
                { 1280, "Pine Wardrobe" },
                { 1281, "Metal Wardrobe" },
                { 1282, "Umbrella / Parasol" },
                { 1283, "Cooler" },
                { 1284, "Maple Rectangular Table" },
                { 1285, "Birch Rectangular Table" },
                { 1286, "Pine Rectangular Table" },
                { 1287, "Metal Rectangular Table" },
                { 1288, "Maple Circular Table" },
                { 1289, "Birch Circular Table" },
                { 1290, "Pine Circular Table" },
                { 1291, "Maple Square Table" },
                { 1292, "Maple Square Table" },
                { 1293, "Birch Square Table" },
                { 1294, "Pine Square Table" },
                { 1295, "Metal Square Table" },
                { 1296, "Beach Chair" },
                { 1297, "Weak Glass" },
                { 1298, "Bulletproof Glass" },
                { 1299, "One Way Glass" },
                { 1300, "Tank Cannon" },
                { 1302, "Missile" },
                { 1303, "Blue Couch" },
                { 1304, "Green Couch" },
                { 1305, "Orange Couch" },
                { 1306, "Purple Couch" },
                { 1307, "Red Couch" },
                { 1308, "Yellow Couch" },
                { 1309, "Blue Cot" },
                { 1310, "Green Cot" },
                { 1311, "Orange Cot" },
                { 1312, "Purple Cot" },
                { 1313, "Red Cot" },
                { 1314, "Yellow Cot" },
                { 1315, "Blue Beach Chair" },
                { 1316, "Green Beach Chair" },
                { 1317, "Orange Beach Chair" },
                { 1318, "Purple Beach Chair" },
                { 1319, "Red Beach Chair" },
                { 1320, "Yellow Beach Chair" },
                { 1321, "Blue Umbrella Barricade" },
                { 1322, "Green Umbrella (Barricade)" },
                { 1323, "Orange Umbrella (Barricade)" },
                { 1324, "Purple Umbrella (Barricade)" },
                { 1325, "Red Umbrella (Barricade)" },
                { 1326, "Yellow Umbrella (Barricade)" },
                { 1327, "Book" },
                { 1328, "Note" },
                { 1329, "Maple Hatch" },
                { 1330, "Birch Hatch" },
                { 1331, "Pine Hatch" },
                { 1332, "Metal Hatch" },
                { 1333, "Russian Military Top" },
                { 1334, "Russian Military Bottom" },
                { 1335, "Russian Military Helmet" },
                { 1336, "Russian Military Vest" },
                { 1337, "Paintball Gun" },
                { 1339, "Blue Paintball Hopper" },
                { 1340, "Green Paintball Hopper" },
                { 1341, "Orange Paintball Hopper" },
                { 1342, "Purple Paintball Hopper" },
                { 1343, "Red Paintball Hopper" },
                { 1344, "Yellow Paintball Hopper" },
                { 1345, "Farming Plot" },
                { 1346, "Flashbang" },
                { 1347, "Raw Minnow" },
                { 1348, "Cooked Minnow" },
                { 1349, "Raw Goldfish" },
                { 1350, "Cooked Goldfish" },
                { 1351, "Raw Bass" },
                { 1352, "Cooked Bass" },
                { 1353, "Stealy Wheely Automobiley" },
                { 1354, "Russian Ghillie Top" },
                { 1355, "Russian Ghillie Bottom" },
                { 1356, "Russian Ghillie Hood" },
                { 1357, "Russian Ghillie Vest" },
                { 1358, "Pilot Top" },
                { 1359, "Pilot Cap" },
                { 1360, "Teklowvka" },
                { 1361, "Teklowvka Magazine" },
                { 1362, "Augewehr" },
                { 1363, "Augewehr Scope" },
                { 1364, "Hells Fury" },
                { 1365, "Hell's Fury Drum" },
                { 1366, "Vonya" },
                { 1367, "Vonya Iron Sights" },
                { 1368, "Vonya Magazine" },
                { 1369, "Bulldog" },
                { 1370, "Bulldog Iron Sights" },
                { 1371, "Bulldog Magazine" },
                { 1372, "Friendly Sentry" },
                { 1373, "Hostile Sentry" },
                { 1375, "Fusilaut" },
                { 1376, "Fusilaut Iron Sights" },
                { 1377, "Nightraider" },
                { 1378, "Nightraider Iron Sights" },
                { 1379, "Calling Card" },
                { 1380, "Calling Card Iron Sights" },
                { 1381, "Calling Card Magazine" },
                { 1382, "Ekho" },
                { 1383, "Ekho Iron Sights" },
                { 1384, "Ekho Magazine" },
                { 1385, "Mafia Fedora" },
                { 1386, "Mafia Tuxedo Top" },
                { 1387, "Mafia Tuxedo Bottom" },
                { 1388, "Russian Beret" },
                { 1389, "Spec Ops Beret" },
                { 1390, "Pool Cue" },
                { 1391, "Tracksuit Top" },
                { 1392, "Tracksuit Bottom" },
                { 1393, "Precision Charge" },
                { 1394, "Heavy Machine Gun (HMG)" },
                { 1395, "Heavy Machine Gun Box (HMG Box)" },
                { 1396, "Ghillie Netting" },
                { 1397, "Russia Ghillie Netting" },
                { 1398, "Trout Sandwich" },
                { 1399, "Salmon Sandwich" },
                { 1400, "Minnow Sandwich" },
                { 1401, "Goldfish Sandwich" },
                { 1402, "Venison Sandwich" },
                { 1403, "Bass Sandwich" },
                { 1404, "Beef Sandwich" },
                { 1405, "Cheese Steak Sandwich" },
                { 1406, "BLT Sandwich" },
                { 1407, "Beef Sandwich (Inorganic)" },
                { 1408, "Cloth Mannequin" },
                { 1409, "Metal Mannequin" },
                { 1410, "Maple Plaque" },
                { 1411, "Birch Plaque" },
                { 1412, "Pine Plaque" },
                { 1413, "Metal Plaque" },
                { 1414, "Maple Ramp Wall" },
                { 1415, "Birch Ramp Wall" },
                { 1416, "Pine Ramp Wall" },
                { 1417, "Metal Ramp Wall" },
                { 1418, "Brick Ramp Wall" },
                { 1419, "Coalition Bottom" },
                { 1420, "Ensign Coalition Top" },
                { 1421, "Lieutenant Coalition Top" },
                { 1422, "Major Coalition Top" },
                { 1423, "Commander Coalition Top" },
                { 1424, "Captain Coalition Top" },
                { 1425, "Coalition Vest" },
                { 1426, "Coalition Cap" },
                { 1427, "Coalition Helmet" },
                { 1428, "Coalition Beret" },
                { 1429, "Coalition Captain Hat" },
                { 1430, "Upgraded Cake Blueprint" },
                { 1431, "Upgraded Cake" },
                { 1432, "Upgraded Fishing Rod" },
                { 1433, "Upgraded Fishing Rod Blueprint" },
                { 1434, "Raw Squid" },
                { 1435, "Cooked Squid" },
                { 1436, "Quadbarrel" },
                { 1437, "Quadbarrel Blueprint" },
                { 1438, "Bayonet" },
                { 1439, "Bayonet Blueprint" },
                { 1440, "Industrial Gas Can" },
                { 1441, "Shadowstalker Mk II (Mk 2)" },
                { 1442, "Shadowstalker Mk II (Mk 2) Scope" },
                { 1443, "Shadowstalker Mk II (Mk 2) Drum" },
                { 1444, "Bluntforce Muffler" },
                { 1445, "Walkie Talkie" },
                { 1446, "Earpiece" },
                { 1447, "Scalar" },
                { 1448, "Scalar Iron Sights" },
                { 1449, "Scalar Magazine" },
                { 1450, "Vehicle Battery" },
                { 1451, "Tire" },
                { 1452, "Whole Coconut" },
                { 1453, "Split Coconut" },
                { 1454, "Black Trunks" },
                { 1455, "Blue Trunks" },
                { 1456, "Green Trunks" },
                { 1457, "Orange Trunks" },
                { 1458, "Purple Trunks" },
                { 1459, "Red Trunks" },
                { 1460, "White Trunks" },
                { 1461, "Yellow Trunks" },
                { 1462, "Coastguard Top" },
                { 1463, "Coastguard Bottom" },
                { 1464, "Blindfold" },
                { 1465, "Picket Sign" },
                { 1466, "Stereo" },
                { 1467, "Maple Placard" },
                { 1468, "Birch Placard" },
                { 1469, "Pine Placard" },
                { 1470, "Metal Placard" },
                { 1471, "(temp) Fighter Jet HMG" },
                { 1472, "Fighter Jet Hat" },
                { 1473, "Fighter Jet Top" },
                { 1474, "Fighter Jet Bottom" },
                { 1475, "Jackhammer" },
                { 1476, "Luger" },
                { 1477, "MP40 Maschinengewehr" },
                { 1479, "MP40 Maschinengewehr Magazine" },
                { 1480, "Determinator" },
                { 1481, "Empire" },
                { 1482, "Empire Iron Sights" },
                { 1483, "Empire Magazine" },
                { 1484, "Devil's Bane" },
                { 1485, "Devil's Bane Magazine" },
                { 1486, "Devil's Bane Iron Sights" },
                { 1487, "Luger Magazine" },
                { 1488, "Swissgewher" },
                { 1489, "Swissgewehr Iron Sights" },
                { 1490, "Swissgewehr Magazine" },
                { 1491, "Military Top" },
                { 1492, "Ghillie Top Peaks" },
                { 1493, "Ghillie Bottom Peaks" },
                { 1494, "Ghillie Hood Peaks" },
                { 1495, "Ghillie Vest Peaks" },
                { 1498, "Lederhosen Top" },
                { 1499, "Lederhosen Bottom" },
                { 1500, "Ghillie Nettings" },
                { 1501, "EA Tee" },
                { 1502, "EA Beret" },
                { 1503, "Zweihander" },
                { 1504, "Pickelhaube" },
                { 1505, "Kaiser Top" },
                { 1506, "Kaiser Bottom" },
                { 1507, "Socketwrench" },
                { 1508, "Compass" },
                { 1509, "Wall Clock" },
                { 1510, "Explosive Chewing Gum" },
                { 1511, "Arctic Alicepack" },
                { 1512, "Arctic Ghillie Top" },
                { 1513, "Arctic Ghillie Bottom" },
                { 1514, "Arctic Ghillie Vest" },
                { 1515, "Arctic Ghillie Hood" },
                { 1516, "Arctic Military Top" },
                { 1517, "Arctic Military Bottom" },
                { 1518, "Arctic Military Vest" },
                { 1519, "Arctic Military Helmet" },
                { 1520, "Impact Grenade" },
                { 1524, "Zero Kelvin Weapon Kit" },
                { 1526, "Lil' EBR Rapper Hoodie (Belgium Update)" },
                { 1527, "Lil EBR Rapper Pants (Belgium Update)" },
                { 1528, "Belgian Infantry Backpack (Belgium)" },
                { 1529, "Belgian Infantry Gear (Belgium)" },
                { 1530, "Belgian Infantry Helmet (Belgium)" },
                { 1531, "Belgian Infantry Top (Belgium)" },
                { 1532, "Belgian Infantry Bottom (Belgium)" },
                { 2010, "Mushroom" },
                { 2011, "Roasted Mushroom" },
                { 2013, "Mushroom P" },
                { 2014, "Obsidian Axe" },
                { 2015, "Obsidian Club" },
                { 2016, "Aegis Security Top" },
                { 2017, "Aegis Security Bottom" },
                { 2018, "Aegis Lab Top" },
                { 2019, "Aegis Lab Bottoms" },
                { 2020, "Shark-Tooth Sword" },
                { 2021, "Raft Makeshift Vehicle" },
                { 2022, "Gyro Makeshift Vehicle" },
                { 3000, "Security Shirt (France)" },
                { 3001, "Security Guard Cap (France)" },
                { 3002, "Carabine (France)" },
                { 3003, "Carabine Sights (France)" },
                { 3004, "Carabine Clip (France)" },
                { 3005, "Musket (France)" },
                { 3006, "Musket Cartridge (France)" },
                { 3007, "Upgraded Musket (France)" },
                { 3008, "Kestrel (France)" },
                { 3009, "Kestrel Sights (France)" },
                { 3010, "Kestrel Magazine (France)" },
                { 3011, "Kestrel Extended Magazine (France)" },
                { 3012, "Extended Masterkey (France)" },
                { 3013, "Extended Masterkey Barrels (France)" },
                { 3014, "Single Shot Shotgun (France)" },
                { 3015, "Military Top Normal (France)" },
                { 3016, "Military Bottom (France)" },
                { 3017, "Military Top Gloved (France)" },
                { 3018, "Military Cargo Bottom (France)" },
                { 3019, "Military Vest (France)" },
                { 3020, "Kepi (France)" },
                { 3021, "French Beret (France)" },
                { 3022, "Military Helmet (France)" },
                { 3023, "Fusilette (France)" },
                { 3024, "Fusilette Sights (France)" },
                { 3025, "Fusilette Magazine (France)" },
                { 3026, "Rubicon (France)" },
                { 3027, "Rubicon Sights (France)" },
                { 3028, "Rubicon Magazine (France)" },
                { 3029, "Riot Uniform Top Light (France)" },
                { 3030, "Riot Uniform Bottom Light (France)" },
                { 3031, "Riot Uniform Top Dark (France)" },
                { 3032, "Riot Uniform Bottom Dark (France)" },
                { 3033, "Rattlesnake (France)" },
                { 3034, "Rattlesnake Barrel (France)" },
                { 3035, "Viper Drum (France)" },
                { 3036, "Banshee (France)" },
                { 3037, "Banshee Sights (France)" },
                { 3038, "Banshee Magazine (France)" },
                { 3039, "Corsican (France)" },
                { 3040, "Corsican Magazine (France)" },
                { 3041, "Genaugewehr (France)" },
                { 3042, "Genaugewehr Sights (France)" },
                { 3043, "Vanguard (France)" },
                { 3044, "Vanguard Sights (France)" },
                { 3045, "Rhino (France)" },
                { 3046, "Rhino Sights (France)" },
                { 3047, "Rhino Box (France)" },
                { 3048, "Rhino Large Box (France)" },
                { 3049, "Hecate (France)" },
                { 3050, "Hecate Sights (France)" },
                { 3051, "Hecate Magazine (France)" },
                { 3052, "Herstal (France)" },
                { 3053, "Herstal Sights (France)" },
                { 3054, "Herstal Magazine (France)" },
                { 3055, "Herstal Drum (France)" },
                { 3056, "Flamethrower (France)" },
                { 3057, "Napalm Tank (France)" },
                { 3058, "Insurgent Gun (France)" },
                { 3059, "Sagaie Cannon (France)" },
                { 3060, "HVAP Shell (France)" },
                { 3061, "Autocannon Single (France)" },
                { 3062, "Autocannon AP Shells (France)" },
                { 3063, "Autocannon Tracer Shells (France)" },
                { 3064, "Autocannon HE Shells (France)" },
                { 3065, "Autocannon Incendiary Shells (France)" },
                { 3066, "Riot Vest Light (France)" },
                { 3067, "Riot Vest Dark (France)" },
                { 3068, "Riot Helmet Light (France)" },
                { 3069, "Riot Helmet Dark (France)" },
                { 3070, "Police Parka (France)" },
                { 3071, "Cheese Wheel (France)" },
                { 3072, "Olive Hecate (France)" },
                { 3073, "10x Scope (France)" },
                { 3074, "Hunting Scope (France)" },
                { 3075, "Autocannon Twin (France)" },
                { 3076, "Police Cargo Pants (France)" },
                { 3077, "Train Gun (France)" },
                { 3078, "Monsieur (France)" },
                { 3079, "Monsieur Clip (France)" },
                { 3080, "Chester (France)" },
                { 3081, "Police Cap (France)" },
                { 3082, "Military Rucksack (France)" },
                { 3083, "Alicepack (France)" },
                { 3084, "Baguette (France)" },
                { 3085, "Stale Baguette (France)" },
                { 3086, "Sawed-Off Stale Baguette (France)" },
                { 3087, "Military Launcher (France)" },
                { 3088, "Military Rocket (France)" },
                { 3089, "Military Launcher Scope (France)" },
                { 3090, "Homemade Napalm Recipe (France)" },
                { 3091, "Makeshift Napalm Tank (France)" },
                { 3092, "Colonel Kepi (France)" },
                { 3093, "Focus Rifle (France)" },
                { 3094, "Focus DMR (France)" },
                { 3095, "Focus Carbine (France)" },
                { 3096, "Focus Rifle Sight (France)" },
                { 3097, "Energy Cell (France)" },
                { 3098, "Riot Cap Light (France)" },
                { 3099, "Riot Cap Dark (France)" },
                { 3100, "Heavy Crossbow (France)" },
                { 3101, "Crossbow Bolt (France)" },
                { 3102, "Heavy_Crossbow_Barrel (France)" },
                { 3103, "Shake_Grip (France)" },
                { 3104, "Ghillie Top (France)" },
                { 3105, "Ghillie Bottom (France)" },
                { 3106, "Ghillie Hood (France)" },
                { 3107, "Ghillie Vest (France)" },
                { 3108, "Kriegs (France)" },
                { 3109, "Kriegs Sights (France)" },
                { 3110, "Kriegs Magazine (France)" },
                { 3111, "Karus (France)" },
                { 3112, "Karus Sights (France)" },
                { 3113, "Karus Drum (France)" },
                { 3114, "Focus Rifle Scope (France)" },
                { 3115, "Ranger Helmet (France)" },
                { 3116, "Focus Prototype (France)" },
                { 3117, "Nutrition Bar (France)" },
                { 3118, "Ghillie Backpack (France)" },
                { 3119, "Cartridge Mold (France)" },
                { 3120, "Musket Coin Shot (France)" },
                { 3121, "Kriegs Extended Magazine (France)" },
                { 3500, "Multiple Launch Rocket System" },
                { 3501, "MLRS Pod" },
                { 3502, "MLRS Rocket" },
                { 3503, "Grasslands Military Top" },
                { 3504, "Grasslands Military Bottom" },
                { 3505, "Lance Corporal Military Top" },
                { 3506, "Corporal Military Top" },
                { 3507, "Sergeant Military Top" },
                { 3508, "Sergeant 1st Class Military Top" },
                { 3509, "Master Sergeant Military Top" },
                { 3510, "Grasslands Military Vest" },
                { 3511, "Military Boonie Cap" },
                { 3512, "Chimera" },
                { 3513, "Chimera Magazine" },
                { 3514, "Chimera Iron Sights" },
                { 3515, "Kopis" },
                { 3516, "Kopis Magazine" },
                { 3517, "Lancer" },
                { 3518, "Lancer Rocket" },
                { 3519, "Lancer Scope" },
                { 3520, "Backlash" },
                { 3521, "Backlash Iron Sights" },
                { 3522, "Lockdown" },
                { 3523, "Lockdown Magazine" },
                { 3524, "Lockdown Iron Sights" },
                { 3525, "Omega Uniform Bottoms" },
                { 3526, "Omega Hoplite Top" },
                { 3527, "Omega Captain Top" },
                { 3528, "Omega Battalion Leader Top" },
                { 3529, "Omega Colonel Top" },
                { 3530, "Omega Brigadier Top" },
                { 3531, "Omega Beanie Cap" },
                { 3532, "Military Beanie Cap" },
                { 3533, "Omega Uniform Top" },
                { 3534, "General Top" },
                { 3535, "Official Top" },
                { 3536, "Grasslands Military Helmet" },
                { 3537, "Police Helmet" },
                { 4000, "Platinum Ring" },
                { 9000, "Thunderwulf (Belgium)" },
                { 9001, "Thunderwulf Mag (Belgium)" },
                { 9002, "Thunderwulf Iron Sights (Belgium)" },
                { 9003, "Vulture (Belgium)" },
                { 9004, "Vulture Iron Sights (Belgium)" },
                { 9005, "Scourge (Belgium)" },
                { 9006, "Scourge Mag (Belgium)" },
                { 9009, "Woodlands Military Top (Belgium)" },
                { 9010, "Woodlands Military Bottom (Belgium)" },
                { 9011, "Woodlands Military Vest (Belgium)" },
                { 9012, "Woodlands Beret (Belgium)" },
                { 9013, "Woodlands Military Helmet (Belgium)" },
                { 9014, "Woodlands Ghillie Top (Belgium)" },
                { 9015, "Woodlands Ghillie Bottom (Belgium)" },
                { 9016, "Woodlands Ghillie Vest (Belgium)" },
                { 9017, "Woodlands Ghillie Hood (Belgium)" },
                { 9018, "Belgium Police Top (Belgium)" },
                { 9019, "Belgium Police Bottom (Belgium)" },
                { 9020, "Belgium Police Vest (Belgium)" },
                { 9021, "Acid Gun (Belgium)" },
                { 9022, "Acid Canister (Belgium)" },
                { 9024, "Alphadragon (Belgium)" },
                { 9025, "Alphadragon Iron Sight (Belgium)" },
                { 9026, "Phoenix (Belgium)" },
                { 9027, "Phoenix Magazine (Belgium)" },
                { 9028, "Hartgewher (Belgium)" },
                { 9029, "Hartgewher Iron Sight (Belgium)" },
                { 9030, "Leistung (Belgium)" },
                { 9031, "Leistung Mag (Belgium)" },
                { 9032, "Belgian Eclair (Belgium)" },
                { 9033, "Slip (Belgium)" },
                { 9034, "Slip Iron Sight (Belgium)" },
                { 9037, "Belgium Prisoner Top (Belgium)" },
                { 9038, "Belgium Prisoner Bottom (Belgium)" },
                { 9039, "Belgium Prisoner Hat (Belgium)" },
                { 9040, "Sailor Top (Belgium)" },
                { 9041, "Sailor Bottom (Belgium)" },
                { 9042, "Sailor Hat (Belgium)" },
                { 9043, "Sailor Captain Top (Belgium)" },
                { 9044, "Sailor Captain Bottom (Belgium)" },
                { 9045, "Sailor Captain Hat (Belgium)" },
                { 9046, "Belgian Creampuff (Belgium)" },
                { 15000, "IFR Top Recruit" },
                { 15001, "IFR Bottom" },
                { 15002, "Beret IFR" },
                { 15003, "Ireland Bottom" },
                { 15004, "Ireland Top Private" },
                { 15005, "Ireland Top Lieutenant" },
                { 15006, "Ireland Top Major" },
                { 15007, "Beret Ireland" },
                { 15009, "Bandana IFR" },
                { 15010, "Asylum Bottom" },
                { 15011, "Asylum Top" },
                { 15012, "Chainmail Top" },
                { 15013, "Chainmail Bottom" },
                { 15014, "IFR Top Officer" },
                { 15015, "IFR Top Commander" },
                { 15020, "Garda Top" },
                { 15021, "Firefighter Top Ireland" },
                { 15022, "Firefighter Bottom Ireland" },
                { 15023, "Prisoner Top Coalition" },
                { 15024, "Prisoner Bottom Coalition" },
                { 15025, "Vest Garda" },
                { 15030, "Butcher Top" },
                { 15031, "Butcher Bottom" },
                { 15032, "Butcher Top Fish" },
                { 15033, "Butcher Bottom Fish" },
                { 15034, "Brewery Top" },
                { 15035, "Brewery Bottom" },
                { 15036, "Wezel" },
                { 15037, "Wezel Iron Sights" },
                { 15038, "Wezel Magazine" },
                { 15039, "Orel" },
                { 15040, "Orel 15 Magazine" },
                { 15041, "Cobalt" },
                { 15042, "Cobalt Iron Sights" },
                { 15043, "Cobalt Magazine" },
                { 15044, "Dagger" },
                { 15045, "Dagger Scope" },
                { 15046, "Dagger Magazine" },
                { 15047, "Orel 35 Magazine" },
                { 15048, "Hospitality" },
                { 15049, "Hospitality Scope" },
                { 15050, "Hollowcharge" },
                { 15052, "Hollowcharge Magazine" },
                { 15053, "Judgement" },
                { 15054, "Judgement Scope" },
                { 15055, "Judgement Magazine" },
                { 15100, "Bottled 4-Leaf" },
                { 15101, "Bottled Coffee" },
                { 23001, "Vityaz (Carpat)" },
                { 23002, "Vityaz Magazine (Carpat)" },
                { 23003, "Vityaz Iron Sights (Carpat)" },
                { 23004, "Wolf Leather (Carpat)" },
                { 23006, "Monster Leather (Carpat)" },
                { 23008, "Condensed Milk (Carpat)" },
                { 23010, "Cucumber (Carpat)" },
                { 23011, "Processor (Carpat)" },
                { 23012, "Video Card (Carpat)" },
                { 23013, "Flash Drive (Carpat)" },
                { 23014, "Lusod Candy (Carpat)" },
                { 23015, "Blueberry Candy (Carpat)" },
                { 23016, "Glaz (Carpat)" },
                { 23017, "Glaz Magazine (Carpat)" },
                { 23537, "Green Dot Sight" },
                { 52000, "HMG" },
                { 52004, "White Hoodie (Blue)" },
                { 52005, "White Hoodie (Red)" },
                { 52006, "White Hoodie (Green)" },
                { 52007, "White Pants (Blue)" },
                { 52008, "White Pants (Red)" },
                { 52009, "White Pants (Green)" },
                { 52010, "White Hat" }
            };
            Dictionary<int, string> moddedItems = new Dictionary<int, string>
            {
                //420's Gold Mod
                { 31620, "$1 Coin" },
                { 31621, "$10" },
                { 31622, "$100" },
                { 31623, "$200" },
                { 31624, "$400" },
                { 31625, "$600" },
                { 31626, "$1000" },
                { 31627, "$1500" },
                { 31614, "Medium Buy Station" },
                { 31600, "Copper Bar" },
                { 31601, "Copper Ore" },
                { 31608, "Diamond" },
                { 31604, "Gold Bar" },
                { 31605, "Gold Ore" },
                { 31606, "Platinum Bar" },
                { 31607, "Platinum Ore" },
                { 31612, "Large Selling Display" },
                { 31611, "Medium Selling Display" },
                { 31610, "Small Selling Display" },
                { 31613, "Weapon Selling Rack" },
                { 31602, "Silver Bar" },
                { 31603, "Silver Ore" },

                //420's Lootboxes
                { 31702, "Rare Loot Crate" },
                { 31703, "Epic Loot Crate" },
                { 31704, "Legendary Loot Crate" },

                //420's Modern Warfare Mod
                { 31379, "4.6x30mm Rounds" },
                { 31380, "Box of 4.6x30mm Rounds" },
                { 31359, "5.7x28mm Rounds" },
                { 31360, "Box of 5.7x28mm Rounds" },
                { 31348, "5.45x39mm Rounds" },
                { 31349, "Box of 5.45x39mm Rounds" },
                { 31342, "5.56x45mm NATO Rounds" },
                { 31344, "Box of 5.56x45mm NATO Rounds" },
                { 31345, "7.62x39mm Rounds" },
                { 31347, "Box of 7.62x39mm Rounds" },
                { 31350, "7.62x51mm NATO Rounds" },
                { 31351, "Box of 7.62x51mm NATO Rounds" },
                { 31367, "7.62x54mmR Rounds" },
                { 31368, "Box of 7.62x54mmR Rounds" },
                { 31353, "9x19mm Rounds" },
                { 31354, "Box of 9x19mm Rounds"},
                { 31394, "9mm Suppressor" },
                { 31361, "12ga 00 Buckshot" },
                { 31363, "12ga Birdshot" },
                { 31362, "12ga Slugs" },
                { 31336, "12rnd .45 ACP Magazine" },
                { 31316, "25rnd .45 ACP Magazine" },
                { 31395, ".45 Suppressor" },
                { 31355, ".45 ACP Rounds" },
                { 31356, "Box of .45 ACP Rounds" },
                { 31352, ".338 Lapua Magnum Rounds" },
                { 31357, ".357 Magnum Rounds" },
                { 31358, "Box of .357 Magnum Rounds" },
                { 31384, ".408 Cheyenne Tactical Rounds" },
                { 31500, "AK Rear Sights" },
                { 31302, "AK-74" },
                { 31303, "5.45x39mm Magazine" },
                { 31300, "AKM" },
                { 31346, "7.62x39mm AK Magazine" },
                { 31301, "AKMS" },
                { 31307, "AKS-74U" },
                { 31334, "AUG A3" },
                { 31534, "AUG A3 Iron Sights" },
                { 31305, "AWM" },
                { 31306, "AWM Magazine" },
                { 31313, "7.62x51mm NATO Magazine (BR_10)" },
                { 31312, "7.62x51mm NATO Magazine (BR_20)" },
                { 31382, "CheyTac M200" },
                { 31383, "M200 Magazine" },
                { 31322 , "FN FAL" },
                { 31522, "FN FAL Rear Sights" },
                { 31370, "G3A3" },
                { 31570, "G3A3 Rear Sights" },
                { 31304, "G36C" },
                { 31504, "G36C Iron Sights" },
                { 31335, "Glock 21" },
                { 31311, "HK417" },
                { 31511, "HK417 Iron Sights" },
                { 31389, "EOTech Holographic" },
                { 31314, "M1A SOCOM" },
                { 31514, "M1A SOCOM Rear Sights" },
                { 31308, "M4A1" },
                { 31508, "M4A1 Carrier Handle" },
                { 31392, "MCX" },
                { 31592, "MCX Iron Sights" },
                { 31337, "S&W Model 686" },
                { 31328, "Mossberg M590A1" },
                { 31324, "MP5 Magazine" },
                { 31523, "MP5 Rear Sights" },
                { 31323, "MP5K" },
                { 31377, "MP7" },
                { 31378, "MP7 Magazine" },
                { 31577, "MP7 Iron Sights" },
                { 31390, "MPX" },
                { 31391, "30rnd MPX Magazine" },
                { 31590, "MPX Iron Sights" },
                { 31332, "P90" },
                { 31333, "P90 Magazine" },
                { 31532, "P90 Iron Sights" },
                { 31326, "P226" },
                { 31327, "9x19mm Magazine" },
                { 31385, "PKM" },
                { 31386, "PKM Box" },
                { 31585, "PKM Rear Sights" },
                { 31318, "R700" },
                { 31319, ".308 Rounds" },
                { 31317, "Remington 870" },
                { 31372, "Saiga-12K Magazine (00 Buckshot)" },
                { 31374, "Saiga-12K Magazine (Birdshot)" },
                { 31373, "Saiga-12K Magazine (Slugs)" },
                { 31371, "Saiga-12K" },
                { 31571, "Saiga12-K Iron Sights" },
                { 31339, "SCAR-L Tan" },
                { 31340, "SCAR-L Black" },
                { 31540, "SCAR-L Black Iron Sights" },
                { 31539, "SCAR-L Tan Iron Sights" },
                { 31331, "SG552 Commando" },
                { 31531, "SG552 Rear Sights" },
                { 31309, "Scorpion EVO 3 A1" },
                { 31310, "Scorpion EVO Magazine" },
                { 31509, "Scorpion EVO Rear Sight" },
                { 31329, "Skorpion vz. 61" },
                { 31330, "Skorpion Magazine" },
                { 31343, "STANAG Magazine" },
                { 31375, "SV-98" },
                { 31376, "SV-98 Magazine" },
                { 31315, "UMP .45" },
                { 31515, "UMP 45 Rear Sight" },
                { 31387, "Vector .45" },
                { 31320, "PP-19 Vityaz" },
                { 31321, "PP-19 Vityaz Magazine" },
                { 31520, "Vityaz Rear Sights" },
                { 31381, "X95 \"Micro\"" },
                { 31581, "X95 Iron Sights" },

                //More Farming Mod
                { 42171, "Apple Pie" },
                { 42172, "Banana Bread" },
                { 42241, "Ale Barrel" },
                { 42242, "Mead Barrel" },
                { 42243, "Wine Barrel" },
                { 41166, "Smoked Beef Jerky" },
                { 41165, "Grilled Beef Steak" },
                { 42251, "Bottled Ale" },
                { 42252, "Bottled Mead" },
                { 42253, "Bottled Wine" },
                { 42254, "Round Bottled Wine" },
                { 42131, "Bun" },
                { 42132, "Hamburger" },
                { 42133, "Cheeseburger" },
                { 43125, "Crab Burger" },
                { 42134, "Fresh Burger" },
                { 43124, "Shrimp Burger" },
                { 42218, "Cola Candy" },
                { 42221, "Orange Candy" },
                { 42219, "Soda Candy" },
                { 42220, "Strawberry Candy" },
                { 41168, "Sliced Cheese" },
                { 41167, "Whole Cheese" },
                { 42102, "Coffee" },
                { 42103, "Cafe Au Lait" },
                { 42104, "Roasted Coffee Beans" },
                { 42261, "Ale Mug" },
                { 42262, "Mead Tankard" },
                { 42263, "Wine Glass" },
                { 42264, "Wine Tankard" },
                { 42130, "French Fries" },
                { 41103, "Fried Eggs" },
                { 41143, "Gelatin" },
                { 41135, "Goat Cheese" },
                { 41134, "Sliced Goat Cheese" },
                { 41133, "Whole Goat Cheese" },
                { 41140, "Piece Goat Cheese Pizza" },
                { 41139, "Sliced Goat Cheese Pizza" },
                { 41138, "Goat Cheese Pizza" },
                { 42188, "Honey" },
                { 42230, "Hot Chocolate" },
                { 41115, "Hotdog" },
                { 42161, "Apple Juice" },
                { 42163, "Banana Milk" },
                { 42165, "Grape Juice" },
                { 42162, "Orange Juice" },
                { 42164, "Strawberry Milk" },
                { 42228, "Marshmallows" },
                { 42200, "Chocolate Muffin" },
                { 42199, "Two Chocolate Muffins" },
                { 42198, "Three Chocolate Muffins" },
                { 42197, "Honey Muffin" },
                { 42196, "Two Honey Muffins" },
                { 42195, "Three Honey Muffins" },
                { 42129, "Popcorn" },
                { 42141, "Vegetable Salad" },
                { 42142, "Sausage Salad" },
                { 42143, "Tuna Salad" },
                { 43121, "Carp Sandwich" },
                { 43123, "Eel Sandwich" },
                { 43122, "Sardine Sandwich" },
                { 41114, "Sausage" },
                { 41121, "Chicken Soup" },
                { 41122, "Mutton Stew" },
                { 41123, "Venison Stew" },
                { 42152, "Sugar" },
                { 42170, "Sweet Roll" },
                { 41150, "Roast Turkey" },
                { 41149, "Whole Roast Turkey" },
                { 43111, "Bottled Dirty Water" },
                { 43105, "Raw Carp" },
                { 43106, "Cooked Carp" },
                { 43115, "Raw King Crab" },
                { 43116, "Cooked King Crab" },
                { 43117, "Raw Eel" },
                { 43118, "Cooked Eel" },
                { 43109, "Raw Sardine" },
                { 43110, "Cooked Sardine" },
                { 43107, "Raw Shrimp" },
                { 43108, "Cooked Shrimp" },
                { 42240, "Empty Barrel" },
                { 47188, "Bathroom Door" },
                { 47189, "Bathroom Window" },
                { 47180, "Bathtub" },
                { 47210, "Counter Bell" },
                { 47200, "Candy Bowl" },
                { 47201, "Marshmallow Bowl" },
                { 47222, "Medicine Cabinet" },
                { 42191, "Candle" },
                { 47270, "Candle Stand" },
                { 47220, "Wall Candle Holder" },
                { 47125, "Birch Dining Chair" },
                { 47126, "Maple Dining Chair" },
                { 47128, "Metal Dining Chair" },
                { 47127, "Pine Dining Chair" },
                { 47129, "Birch Saloon Chair" },
                { 47130, "Maple Saloon Chair" },
                { 47132, "Metal Saloon Chair" },
                { 47131, "Pine Saloon Chair" },
                { 47121, "Birch Stool" },
                { 47122, "Maple Stool" },
                { 47124, "Metal Stool" },
                { 47123, "Pine Stool" },
                { 47243, "Christmas Tinsel" },
                { 47240, "Christmas Tree" },
                { 47242, "Christmas Wreath" },
                { 47115, "Birch Coaster" },
                { 47116, "Maple Coaster" },
                { 47117, "Pine Coaster" },
                { 47119, "Coffee Cup" },
                { 47231, "Chicken Coop" },
                { 47266, "Leather Couch" },
                { 47268, "Dark Leather Couch" },
                { 47269, "Single Dark Leather Couch" },
                { 47267, "Single Leather Couch" },
                { 47168, "Birch Cupboard" },
                { 47169, "Maple Cupboard" },
                { 47171, "Metal Cupboard" },
                { 47170, "Pine Cupboard" },
                { 47111, "Birch Dish" },
                { 47112, "Maple Dish" },
                { 47114, "Metal Dish" },
                { 47113, "Pine Dish" },
                { 47107, "Saloon Door" },
                { 47102, "Birch Sliding Door" },
                { 47101, "Maple Sliding Door" },
                { 47104, "Metal Sliding Door" },
                { 47103, "Pine Sliding Door" },
                { 47150, "Birch Fence" },
                { 47160, "Birch Fence Door" },
                { 47161, "Maple Fence Door" },
                { 47162, "Pine Fence Door" },
                { 47155, "Birch Fence Gate" },
                { 47156, "Maple Fence Gate" },
                { 47157, "Pine Fence Gate" },
                { 47151, "Maple Fence" },
                { 47152, "Pine Fence" },
                { 47232, "Fire Barrel" },
                { 47109, "Fireplace" },
                { 47224, "Firewood Rack" },
                { 47140, "Micro Generator" },
                { 47141, "Micro Oxygenator" },
                { 47142, "Windmill Generator" },
                { 47262, "Blue Gift Box" },
                { 47261, "Green Gift Box" },
                { 47260, "Red Gift Box" },
                { 47263, "Yellow Gift Box" },
                { 47145, "Heavy Gun Rack" },
                { 47137, "Boat Hangar Door" },
                { 47136, "Helicopter Hangar Door" },
                { 47135, "Plane Hangar Door" },
                { 47217, "Rampart Door" },
                { 47134, "Tank Hangar Door" },
                { 47199, "Ceiling Fan" },
                { 47198, "Fluorescent Light" },
                { 47197, "Ceiling Light" },
                { 47196, "Mirror Light" },
                { 47195, "Round Wall Lamp" },
                { 47106, "Loom" },
                { 47252, "Blue Ball Ornament" },
                { 47249, "Gold Ball Ornament" },
                { 47253, "Green Ball Ornament" },
                { 47251, "Red Ball Ornament" },
                { 47250, "Silver Ball Ornament" },
                { 47245, "Bell Ornament" },
                { 47246, "Candy Cane" },
                { 47248, "Green Christmas Stocking" },
                //{ 47263, "" },
                //{ 47263, "" },
                //{ 47263, "" },
                //{ 47263, "" },
                //{ 47263, "" },
                //{ 47263, "" },
                //{ 47263, "" },
                //{ 47263, "" },
                //{ 47263, "" },
                //{ 47263, "" },
                //{ 47263, "" },
                //{ 47263, "" },
                //{ 47263, "" },
                //{ 47263, "" },
                //{ 47263, "" },
                //{ 47263, "" },
                //{ 47263, "" },
                //{ 47263, "" },
                //{ 47263, "" },
                //{ 47263, "" },
                //{ 47263, "" },
                //{ 47263, "" },
                //{ 47263, "" },
                //{ 47263, "" },
                //{ 47263, "" },
                //{ 47263, "" }

                //GoldGaming's Locker Pack
                { 17325, "Large Locker" },
                { 17326, "Huge Locker" },
                { 17327, "Massive Locker" },

                //Item Stacking
                { 14222, "Bolt Of Cloth" },
                { 14242, "Box Of Nails" },
                { 14232, "Box Of Tape" },
                { 14282, "Crate Of Explosives" },
                { 14292, "Crate Of Grenades" },
                { 14302, "Crate Of Rockets" },
                { 14312, "Drum Of Chemicals" },
                { 14322, "Jug Of Glue" },
                { 14342, "Spool Of Rope" },
                { 14352, "Spool Of Wire" },
                { 14272, "Case Of Water" },

                //Item Supply
                { 62646, "Elite Coin" },
                { 62647, "Elite Coin Stack" },
                { 62656, "PvP Coin" },
                { 62657, "PvP Coin Stack" },
                { 62626, "Standard Coin" },
                { 62627, "Standard Coin Stack" },
                { 62636, "Superior Coin" },
                { 62637, "Superior Coin Stack" },
                { 62526, "Sewing Kit" },

                //Toxicity Backpacks
                { 7636, "Toxicity Assassin Pack" },
                { 7648, "Toxicity Godlike Freighter Pack" },
                { 7647, "Toxicity Immortal Freighter Pack" },
                { 7646, "Toxicity Legendary Freighter Pack" },
                { 7645, "Toxicity Mighty Freighter Pack" },
                { 7627, "Toxicity Mercenary Alice" },
                { 7625, "Toxicity Ranger Alice" },
                { 7626, "Toxicity Soldier Alice" },
                { 7637, "Toxicity SpecOps Pack" },
                { 7635, "Toxicity Warrior Pack" },

                //TACTICOOL Vanilla Gun Pack
                { 6963, "Werbell Suppressor" },
                { 6960, "Boxer" },
                { 6962, "Buzzard Magazine" },
                { 6961, "Buzzard" },
                { 6964, "Desertfox" },
                { 6973, "Disruptor" },
                { 6966, "Greaser Magazine" },
                { 6965, "Greaser" },
                { 6972, "Jerusalem" },
                { 6976, "Jerusalem Iron Sights" },
                { 6967, "Kestrel" },
                { 6968, "Kestrel Magazine" },
                { 6974, "Longranger" },
                { 6975, "Longranger Magazine" },
                { 6969, "Lynx" },
                { 6970, "Raffica" },
                { 6971, "Raffica Magazine" },

                //Oppressor's Gun Pack
                { 7116, "Launcher HE-Rocket" },
                { 7115, "AT4" },
                { 7182, "Internal Suppressor" },
                { 7132, "Pistol Suppressor" },
                { 7117, "Bobcat" },
                { 7118, "Bobcat Magazine" },
                { 7100, "Doubleagent" },
                { 7101, "Doubleagent Magazine" },
                { 7114, "Eagleranger" },
                { 7120, "Goliath" },
                { 7121, "Goliath Box" },
                { 7122, "Goliath Iron Sights" },
                { 7107, "Légerfusil" },
                { 7108, "Légerfusil Magazine" },
                { 7109, "Légerfusil Iron Sights" },
                { 7126, "Lionfish" },
                { 7127, "Lionfish Drum" },
                { 7128, "Lionfish Iron Sights" },
                { 7106, "Mustang" },
                { 7112, "Nikonov" },
                { 7113, "Nikonov Iron Sights" },
                { 7110, "Shino" },
                { 7111, "Shino Magazine" },
                { 7104, "Solvak" },
                { 7105, "Solvak Magazine" },
                { 7102, "Spade" },
                { 7103, "Spade Clip" },
                { 7123, "Sparrow" },
                { 7129, "Taipan" },
                { 7130, "Taipan Magazine" },
                { 7131, "Taipan Iron Sights" },
                { 7119, "Wraith" }
            };
            try
            {
                return unturnedItems[itemID];
            }
            catch
            {
                try
                {
                    return moddedItems[itemID];
                }
                catch
                {
                    return "Unknown";
                }
            }
        }
        public static WeaponMetadata getWeapon(byte[] bytes)
        {
            bool tacticalEnabled = false;
            if (bytes[12] == 1)
            {
                tacticalEnabled = true;
            }
            return new WeaponMetadata
            {
                sight = new Sight
                {
                    durability = bytes[13],
                    ID = MD.FromDualByte(bytes[0], bytes[1])
                },
                tactical = new Tactical
                {
                    durability = bytes[14],
                    ID = MD.FromDualByte(bytes[2], bytes[3]),
                    enabled = tacticalEnabled
                },
                grip = new Grip
                {
                    durability = bytes[15],
                    ID = MD.FromDualByte(bytes[4], bytes[5])
                },
                barrel = new Barrel
                {
                    durability = bytes[16],
                    ID = MD.FromDualByte(bytes[6], bytes[7])
                },
                ammo = new Ammo
                {
                    durability = bytes[17],
                    ID = MD.FromDualByte(bytes[8], bytes[9]),
                    ammoCount = bytes[10]
                },
                firerate = (FireRate)bytes[11]
            };
        }
        public static WaterItemMetadata getWaterContainer(byte[] bytes)
        {
            return new WaterItemMetadata
            {
                WaterType = (Unturned.Water)bytes[0]
            };
        }
        public static TogglableItemMetadata getTogglable(byte[] bytes)
        {
            if(bytes[0] == 0)
            {
                return new TogglableItemMetadata { enabled = false };
            } else
            {
                return new TogglableItemMetadata { enabled = true };
            }
        }
        public static GasItemMetadata getGasContainer(byte[] bytes)
        {
            return new GasItemMetadata
            {
                gasVolume = MD.FromDualByte(bytes[0], bytes[1])
            };
        }
        public static OtherMetadata getOther(byte[] bytes)
        {
            return new OtherMetadata { metadata = bytes };
        }
        public static ItemType dictItemType(ushort ItemID)
        {
            Dictionary<ushort, ItemType> itemTypes = new Dictionary<ushort, ItemType>
            {
                { 481, ItemType.Water },
                { 482, ItemType.Water },
                { 483, ItemType.Water },
                { 337, ItemType.Water },
                { 28, ItemType.Gas },
                { 1440, ItemType.Gas },
                { 334, ItemType.Togglable },
                { 1044, ItemType.Togglable }
            };
            try
            {
                return itemTypes[ItemID];
            } 
            catch
            {
                return ItemType.Other;
            }
        }
    }
    public class MD
    {
        public static (byte, byte) ToDualByte(ushort id)
        {
            return ((byte)(id % 256), (byte)Math.Floor((double)(id / 256)));
        }
        public static ushort FromDualByte(byte byte1, byte byte2)
        {
            return (ushort)((byte2 * 256) + byte1);
        }
    }

    [Description("For weapon attachments")]
    public class WeaponMetadata
    {
        public Sight sight;
        public Tactical tactical;
        public Grip grip;
        public Barrel barrel;
        public Ammo ammo;
        public Unturned.FireRate firerate;

        [Description("Get the byte array metadata from a weapon object.")]
        public byte[] Metadata()
        {
            List<byte> wmet = new List<byte> { };
            (byte, byte) sightIds = MD.ToDualByte(this.sight.ID);
            (byte, byte) tacticalIds = MD.ToDualByte(this.tactical.ID);
            (byte, byte) gripIds = MD.ToDualByte(this.grip.ID);
            (byte, byte) barrelIds = MD.ToDualByte(this.barrel.ID);
            (byte, byte) ammoIds = MD.ToDualByte(this.ammo.ID);
            #region addStuff
            wmet.Add(sightIds.Item1); //Sight
            wmet.Add(sightIds.Item2);

            wmet.Add(tacticalIds.Item1); //Tactical
            wmet.Add(tacticalIds.Item2);

            wmet.Add(gripIds.Item1); //Grip
            wmet.Add(gripIds.Item2);

            wmet.Add(barrelIds.Item1); //Barrel
            wmet.Add(barrelIds.Item2);

            wmet.Add(ammoIds.Item1); //Ammo
            wmet.Add(ammoIds.Item2);

            wmet.Add(ammo.ammoCount); //Ammo Count

            wmet.Add((byte)firerate); //Fire Type

            if(this.tactical.enabled) //Tactical State
            {
                wmet.Add(1);
            } else
            {
                wmet.Add(0);
            }

            wmet.Add(this.sight.durability); //Sight Durability

            wmet.Add(this.tactical.durability); //Tactical Durability

            wmet.Add(this.grip.durability); //Grip Durability

            wmet.Add(this.barrel.durability); //Barrel Durability

            wmet.Add(this.ammo.durability); //Ammo Durability
            #endregion
            return wmet.ToArray();
        }
    }

    [Description("Other Item")]
    public class OtherMetadata
    {
        public byte[] metadata;

        [Description("Get the byte array metadata miscellaneous items.")]
        public byte[] Metadata()
        {
            return this.metadata;
        }
    }

    [Description("Gas Storage Items")]
    public class GasItemMetadata
    {
        public ushort gasVolume;

        [Description("Get the byte array metadata from a Gas Storage object.")]
        public byte[] Metadata()
        {
            return new List<byte> { MD.ToDualByte(this.gasVolume).Item1, MD.ToDualByte(this.gasVolume).Item2 }.ToArray();
        }
    }

    [Description("Water Storage Items")]
    public class WaterItemMetadata
    {
        public Unturned.Water WaterType;

        [Description("Get the byte array metadata from a Water Storage object.")]
        public byte[] Metadata()
        {
            return new List<byte> { (byte)WaterType }.ToArray();
        }
    }

    [Description("For items like night vision that only have enabled or disabled.")]
    public class TogglableItemMetadata
    {
        public bool enabled;

        [Description("Get the byte array metadata from a togglable object.")]
        public byte[] Metadata()
        {
            if(this.enabled)
            {
                return new List<byte> { 1 }.ToArray();
            }
            else
            {
                return new List<byte> { 0 }.ToArray();
            }
        }
    }
    public class Attachment
    {
        public ushort ID;
        public byte durability;
    }
    public class Sight : Attachment
    {
    }
    public class Tactical : Attachment
    {
        public bool enabled = false;
    }
    public class Grip : Attachment
    {
    }
    public class Barrel : Attachment
    {
    }
    public class Ammo : Attachment
    {
        public byte ammoCount = 255;
    }
}
